account/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    ]

todo/urls.py
from django.urls import path
from . import views
app_name = "todos"

urlpatterns = [
    path("", views.list, name="list"),
    path("create/", views.create, name="create"),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("account.urls")),
    path("todos/", include("todo.urls")),
]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
# 장고의 기본설정
from django.conf import settings
# Create your models here.
class Todo(models.Model):
    # 기본적으로 장고에서 가지고 있는 user모델
    # 유저정보 삭제되면 밑에 게시물도 다 지워지게끔
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import Todo

class TodoModelForm(forms.ModelForm):
    class Meta:
        model = Todo
        # fields = '__all__'
        fields = ['title']

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# 우리가 가져온 로그인 이름을 auth_login으로 바꿔줌(이름이 중복이되니까)
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save() # 유효성검사 통과하면 저장
            auth_login(request, user)
            return redirect("todos:list")
    else:
        form = UserCreationForm()
    return render(request,"account/form.html",{"form":form})
    
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            # 사용자의 데이터를 넣어주기
            auth_login(request, form.get_user())
            return redirect("todos:list")
    else:
        form = AuthenticationForm()
    return render(request,"account/form.html",{"form":form})

def logout(request):
    auth_logout(request)
    # 로그아웃하면 로그인페이지로 가도록
    return redirect("accounts:login")

todo/views.py
from django.shortcuts import render, redirect
from .forms import TodoModelForm
from django.contrib.auth.decorators import login_required
from .models import Todo
# Create your views here.
@login_required
def list(request):
    # todos = Todo.objects.all()
    todos = request.user.todo_set.all() # 현재 로그인한 사람의 정보만 볼 수 있음.
    # 전체 todo 목록이 나오는 곳
    return render(request, "todo/list.html",{"todos":todos})
    
@login_required
def create(request):
    if request.method == "POST":
        form = TodoModelForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False) # 자동으로 저장됨. (잠깐 지연하고,,)
            todo.user = request.user # 포스트, 유저, 모든 데이터를 저장하고 있음
            todo.save()
            return redirect("todos:list")
    else:
        form = TodoModelForm()
    return render(request, "todo/create.html", {"form":form})
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <ul>
        {% if user.is_authenticated %}
            <p>로그인함</p>
            <p>{{user}}님 안녕하세요 !!!</p>
            <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
        {% else %}
            <!--사용자가 로그인 안했을 때-->
            <li><a href="{% url 'accounts:signup' %}">회원가입</a></li>
            <li><a href="{% url 'accounts:login' %}">로그인</a></li>
        {% endif %}
            <li><a href="{% url 'todos:create' %}">글작성</a></li>
            <li><a href="{% url 'todos:list' %}">글보기</a></li>
    </ul>
    {% block body_block %}
    {% endblock %}
</body>
</html>

todo/templates/todo/create.html
{% extends "base.html" %}
{% block body_block %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

todo/templates/todo/list.html
{% extends "base.html" %}
{% block body_block %}
    <h1>여기는 리스트입니다!!</h1>
    {% for todo in todos %}
        <p>
        {{todo.title}}
        </p>
    {% endfor %}
{% endblock %}